package org.comp;

import java_cup.runtime.Symbol;

parser code {:

:};

terminal PLUS, MINUS, TIMES, DIVIDE;
terminal LPAREN, RPAREN;
terminal Integer NUMBER;

non terminal Integer expr;

precedence left PLUS, MINUS;
precedence left TIMES, DIVIDE;

start with expr;

expr ::=
      expr:e1 PLUS expr:e2
        {: RESULT = e1 + e2; :}
    | expr:e1 MINUS expr:e2
        {: RESULT = e1 - e2; :}
    | expr:e1 TIMES expr:e2
        {: RESULT = e1 * e2; :}
    | expr:e1 DIVIDE expr:e2
        {: RESULT = e1 / e2; :}
    | LPAREN expr:e RPAREN
        {: RESULT = e; :}
    | NUMBER:n
        {: RESULT = n; :}
    ;